services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]